services:
  db:
    image: postgres:latest
    container_name: catalog-music-simple
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog-music-simple
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
