services:
  db:
    image: postgres:latest
    container_name: catalog-music-simple
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalog-music-simple
    volumes:
      - ./data:/var/lib/postgresql/data
